spring:
  security:
    user:
      name: user
      password: user12#$
  thymeleaf:
#    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
#    cache: false
  devtools:
    livereload:
      enabled: true
